# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('display_url', models.URLField()),
                ('media_url', models.URLField()),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('favorites_count', models.BigIntegerField()),
                ('followers_count', models.BigIntegerField()),
                ('friends_count', models.BigIntegerField()),
                ('twitter_id', models.BigIntegerField()),
                ('statuses_count', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('time_zone', models.CharField(max_length=250, null=True)),
                ('lang', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('favorite_count', models.BigIntegerField()),
                ('twitter_id', models.BigIntegerField()),
                ('in_reply_to_screen_name', models.CharField(max_length=250, null=True)),
                ('in_reply_to_user_id', models.BigIntegerField(null=True)),
                ('is_quote_status', models.BooleanField()),
                ('retweet_count', models.BigIntegerField()),
                ('retweeted', models.BooleanField()),
                ('text', models.CharField(max_length=250)),
                ('timestamp_ms', models.BigIntegerField()),
                ('lang', models.CharField(max_length=10)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('hashtags', models.ManyToManyField(to='twitter_livestream.Hashtag')),
                ('media', models.ManyToManyField(to='twitter_livestream.Media')),
                ('track', models.ManyToManyField(to='twitter_livestream.Track')),
            ],
        ),
        migrations.CreateModel(
            name='TweetQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('tracks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('display_url', models.URLField()),
                ('expanded_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='urls',
            field=models.ManyToManyField(to='twitter_livestream.URL'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter_livestream.TUser'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_mentions',
            field=models.ManyToManyField(related_name='mentions', to='twitter_livestream.TUser'),
        ),
    ]
