# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('display_url', models.URLField()),
                ('media_url', models.URLField()),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('favorites_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('twitter_id', models.IntegerField()),
                ('statuses_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('time_zone', models.CharField(max_length=250)),
                ('lang', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('favorite_count', models.IntegerField()),
                ('twitter_id', models.IntegerField()),
                ('in_reply_to_screen_name', models.CharField(max_length=250)),
                ('in_reply_to_user_id', models.IntegerField()),
                ('is_quote_status', models.BooleanField()),
                ('retweet_count', models.IntegerField()),
                ('retweeted', models.BooleanField()),
                ('text', models.CharField(max_length=250)),
                ('timestamp_ms', models.IntegerField()),
                ('lang', models.CharField(max_length=10)),
                ('hashtags', models.ManyToManyField(to='twitter_livestream.Hashtag')),
                ('media', models.ManyToManyField(to='twitter_livestream.Media')),
                ('t_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter_livestream.TUser')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('display_url', models.URLField()),
                ('expanded_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='urls',
            field=models.ManyToManyField(to='twitter_livestream.URL'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_mentions',
            field=models.ManyToManyField(related_name='mentions', to='twitter_livestream.TUser'),
        ),
    ]
