# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_livestream', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='t_user',
            new_name='user',
        ),
    ]
