# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_livestream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
